/* Deterministic numerical tests. No external test runner or packages. */
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
for(const name of ['locales','i18n','math','geometry','csg','storage'])vm.runInThisContext(fs.readFileSync(path.join(__dirname,'../src',name+'.js'),'utf8'),{filename:name+'.js'});
FI.setLanguage('fr',false);
const checks=[];
function test(name,fn){const t=Date.now();try{fn();checks.push({name,ok:true,ms:Date.now()-t});console.log('PASS',name);}catch(e){checks.push({name,ok:false,error:e.message});console.error('FAIL',name,e.message);}}
const close=(a,b,tol=.02)=>assert(Math.abs(a-b)<=tol,`${a} != ${b}`);
const bytes=p=>{const b=fs.readFileSync(path.join(__dirname,'../examples',p));return b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength);};
const shift=(g,p)=>FG.transform(g,FM.compose(p,[0,0,0,1],[1,1,1]));
for(const type of Object.keys(FG.defaults))test('Primitive fermée, orientations et volume : '+type,()=>{const a=FG.analyze(FG.primitive(type));assert(a.closed);assert(a.signedVolume>0);});
const box=FG.primitive('box',{w:20,d:20,h:20}),offset=shift(box,[10,0,0]);
for(const [op,expected] of [['union',12000],['subtract',4000],['intersect',4000]])test('CSG '+op+' : volume analytique et fermeture',()=>{const a=FG.analyze(FCSG.run(box,offset,op));close(a.volume,expected);assert(a.closed);});
const drill=FG.primitive('cylinder',{r:4,h:40,segments:32});let bored;
test('Perçage traversant : fermé et volume du prisme polygonal',()=>{bored=FCSG.run(box,drill,'subtract');const a=FG.analyze(bored);assert(a.closed);close(a.volume,8000-20*32/2*16*Math.sin(2*Math.PI/32));});
for(const binary of [true,false])test('STL '+(binary?'binaire':'ASCII')+' : aller-retour exact',()=>{const out=FG.exportSTL([bored],binary),buf=binary?out:new TextEncoder().encode(out).buffer,g=FG.parseSTL(buf);assert.equal(g.positions.length,bored.positions.length);close(FG.analyze(g).volume,FG.analyze(bored).volume,.01);assert(FG.analyze(g).closed);});
test('STL binaire dont l’en-tête commence par solid',()=>{const b=FG.exportSTL([box],true);new Uint8Array(b).set(new TextEncoder().encode('solid not-ascii'));assert.equal(FG.parseSTL(b).positions.length,108);});
test('Conversion pouces → millimètres',()=>{const g=FG.parseSTL(FG.exportSTL([box],true),25.4);close(g.bounds.size[0],508);close(FG.analyze(g).volume,8000*Math.pow(25.4,3),1);});
test('Refus d’un fichier invalide, sans triangles ou NaN',()=>{assert.throws(()=>FG.parseSTL(new ArrayBuffer(25)));assert.throws(()=>FG.geometry(new Float32Array(0)));const p=box.positions.slice();p[2]=NaN;assert.throws(()=>FG.geometry(p));});
test('Miroir avec orientation conservée',()=>{const a=FG.analyze(FG.transform(box,FM.compose([3,0,7],[0,0,0,1],[-1,1,1]),true));assert(a.closed);close(a.signedVolume,8000);});
test('Transformation non uniforme et rotation → STL',()=>{const m=FM.compose([25,-12,40],FM.qeuler([18,32,60]),[2,1,3]),g=FG.transform(box,m),r=FG.parseSTL(FG.exportSTL([g],true));close(FG.analyze(r).volume,48000,.1);for(let i=0;i<3;i++)close(r.bounds.center[i],g.bounds.center[i],.0001);});
let top=0;for(let i=0;i<box.positions.length;i+=9){const p=box.positions;const n=FM.norm(FM.cross(FM.sub(Array.from(p.subarray(i+3,i+6)),Array.from(p.subarray(i,i+3))),FM.sub(Array.from(p.subarray(i+6,i+9)),Array.from(p.subarray(i,i+3)))));if(n[2]>.99){top=i/9;break;}}
for(const distance of [5,-5])test('Extrusion de face plane '+distance+' mm',()=>{const patch=FG.planarPatch(box,top);assert.equal(patch.ids.length,2);const g=FCSG.run(box,FG.patchPrism(box,patch,distance),distance>0?'union':'subtract'),a=FG.analyze(g);assert(a.closed);close(a.volume,8000+400*distance);});
test('Découpe en deux solides fermés',()=>{const tool=shift(FG.primitive('box',{w:50,d:50,h:25}),[0,0,12.5]);for(const op of ['subtract','intersect']){const a=FG.analyze(FCSG.run(box,tool,op));assert(a.closed);close(a.volume,4000);}});
test('Subdivision ×4 conserve le volume et la fermeture',()=>{const g=FG.subdivide(box),a=FG.analyze(g);assert.equal(g.positions.length,box.positions.length*4);assert(a.closed);close(a.volume,8000);});
test('Séparation des composantes déconnectées',()=>{const far=shift(box,[50,0,0]),p=new Float32Array(box.positions.length*2);p.set(box.positions);p.set(far.positions,box.positions.length);const parts=FG.connected(FG.geometry(p));assert.equal(parts.length,2);parts.forEach(g=>assert(FG.analyze(g).closed));});
test('Nettoyage de triangles dupliqués',()=>{const p=new Float32Array(box.positions.length+9);p.set(box.positions);p.set(box.positions.subarray(0,9),box.positions.length);const r=FG.clean(FG.geometry(p));assert.equal(r.removed,1);assert(FG.analyze(r.geo).closed);});
test('Maillage ouvert refusé par les booléens',()=>{const g=FG.geometry(box.positions.slice(9));assert(!FG.analyze(g).closed);assert.throws(()=>FCSG.run(g,drill,'subtract'),/fermés/);});
test('Garde-fou 80 000 triangles',()=>{const large=FG.geometry(new Float32Array(90000*9).fill(1));assert.throws(()=>FCSG.run(large,box,'union'),/80 000/);});
test('Projet JSON : géométrie, transformations, paramètres, visibilité',()=>{const state={name:'Projet de test',objects:[{id:'one',name:'Une pièce',geo:box,position:[1,2,3],rotation:FM.qeuler([10,20,30]),scale:[2,3,4],color:'#aabbcc',visible:false,locked:true,hole:true,smooth:true,param:{type:'box',args:{w:20,d:20,h:20}}}]};const out=FStore.unpack(JSON.parse(JSON.stringify(FStore.pack(state,false))));assert.equal(out.name,state.name);const o=out.objects[0];assert.deepEqual(o.position,[1,2,3]);assert.deepEqual(o.scale,[2,3,4]);assert.deepEqual(o.geo.positions,box.positions);assert(o.locked&&o.hole&&!o.visible&&o.smooth);assert.equal(o.param.type,'box');});
test('Projet JSON : format et transformations invalides refusés',()=>{assert.throws(()=>FStore.unpack({format:'wrong'}));});
test('STL de démonstration réimporté puis repercé : fermé',()=>{const g=FG.parseSTL(bytes('support_de_fixation.stl')),tool=shift(FG.primitive('cylinder',{r:5,h:20,segments:24}),[0,-5,4]),before=FG.analyze(g),after=FG.analyze(FCSG.run(g,tool,'subtract'));assert(before.closed&&after.closed);assert(after.volume<before.volume);});
const report={runAt:new Date().toISOString(),node:process.version,checks,passed:checks.filter(t=>t.ok).length,failed:checks.filter(t=>!t.ok).length};fs.writeFileSync(path.join(__dirname,'geometry-results.json'),JSON.stringify(report,null,2));console.log(`\n${report.passed}/${checks.length} tests passed`);if(report.failed)process.exitCode=1;
