/* FORMA 3D — triangle meshes, parametric primitives, STL I/O, topology and local editing. */
'use strict';
var FG = (()=>{
  const {add,sub,mul,dot,cross,len,norm,lerp,bounds,point,uid,clamp}=FM;
  const EPS=1e-5, MAX_TRIANGLES=1200000;
  function geometry(positions){const cached=positions?.csgPolygons;positions=positions?.positions||positions;const p=positions instanceof Float32Array?positions:new Float32Array(positions);if(!p.length||p.length%9)throw Error(FI.t("Le maillage est vide ou incomplet."));if(p.length/9>MAX_TRIANGLES)throw Error(FI.t("Limite : 1 200 000 triangles par objet."));for(const v of p)if(!Number.isFinite(v)||Math.abs(v)>1e8)throw Error(FI.t("Coordonnées non valides ou hors limites."));return {id:uid(),positions:p,bounds:bounds(p),...(cached?{csgPolygons:cached}:{})};}
  function tri(out,a,b,c){const n=cross(sub(b,a),sub(c,a));if(dot(n,n)>1e-18)out.push(...a,...b,...c);}
  function quad(out,a,b,c,d){tri(out,a,b,c);tri(out,a,c,d);}
  function center(g){const c=g.bounds.center,p=g.positions.slice();for(let i=0;i<p.length;i+=3)for(let k=0;k<3;k++)p[i+k]-=c[k];const result=geometry(p);if(g.csgPolygons)result.csgPolygons=g.csgPolygons.map(poly=>poly.map(v=>sub(v,c)));return result;}
  function transform(g,m,reverse=false){const p=new Float32Array(g.positions.length);for(let i=0;i<p.length;i+=3)p.set(point(m,g.positions.subarray(i,i+3)),i);if(reverse)for(let i=0;i<p.length;i+=9)for(let k=0;k<3;k++)[p[i+3+k],p[i+6+k]]=[p[i+6+k],p[i+3+k]];const result=geometry(p);if(g.csgPolygons)result.csgPolygons=g.csgPolygons.map(poly=>{const q=poly.map(v=>point(m,v));return reverse?q.reverse():q;});return result;}
  function normal(a,b,c){return norm(cross(sub(b,a),sub(c,a)));}
  function normals(g,smooth=false){const p=g.positions,n=new Float32Array(p.length),keys=smooth?new Map():null;for(let i=0;i<p.length;i+=9){const v=normal(p.subarray(i,i+3),p.subarray(i+3,i+6),p.subarray(i+6,i+9));for(let j=0;j<3;j++){const o=i+j*3;n.set(v,o);if(keys){const key=keyOf(p,o);if(!keys.has(key))keys.set(key,[]);keys.get(key).push(o);}}}if(keys){const original=n.slice();for(const offsets of keys.values())for(const o of offsets){const a=original.subarray(o,o+3),v=[0,0,0];for(const k of offsets){const b=original.subarray(k,k+3);if(dot(a,b)>.55)for(let j=0;j<3;j++)v[j]+=b[j];}n.set(norm(v),o);}}return n;}
  function keyOf(p,o=0,e=EPS){return Math.round(p[o]/e)+','+Math.round(p[o+1]/e)+','+Math.round(p[o+2]/e);}
  const defaults={box:{w:30,d:30,h:30},cylinder:{r:15,h:30,segments:48},sphere:{r:18,segments:40},cone:{r:18,top:0,h:35,segments:48},tube:{r:18,inner:12,h:25,segments:48},torus:{r:18,t:5,segments:48},prism:{r:18,sides:6,h:25},wedge:{w:35,d:30,h:25},rounded:{w:50,d:35,h:8,r:6,segments:10},gear:{r:22,root:17,teeth:16,h:8},sketch:{points:[[-15,-10],[15,-10],[15,5],[0,20],[-15,5]],h:15}};
  function polygonArea(p){let a=0;for(let i=0;i<p.length;i++){const q=p[(i+1)%p.length];a+=p[i][0]*q[1]-q[0]*p[i][1];}return a/2;}
  const cross2=(a,b,c)=>(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);
  function validatePolygon(p){if(p.length<3)throw Error(FI.t("Dessinez au moins trois points."));if(p.length>500)throw Error(FI.t("Maximum : 500 sommets par esquisse."));for(const q of p)if(!Array.isArray(q)||q.length!==2||!q.every(Number.isFinite))throw Error(FI.t("Point d’esquisse invalide."));for(let i=0;i<p.length;i++)if(len(sub(p[i],p[(i+1)%p.length]))<EPS)throw Error(FI.t("Deux points de l’esquisse sont confondus."));for(let i=0;i<p.length;i++)for(let j=i+1;j<p.length;j++){if(j===i+1||(i===0&&j===p.length-1))continue;const a=p[i],b=p[(i+1)%p.length],c=p[j],d=p[(j+1)%p.length];const ab1=cross2(a,b,c),ab2=cross2(a,b,d),cd1=cross2(c,d,a),cd2=cross2(c,d,b);if(ab1*ab2<=0&&cd1*cd2<=0&&Math.max(Math.min(a[0],b[0]),Math.min(c[0],d[0]))<=Math.min(Math.max(a[0],b[0]),Math.max(c[0],d[0]))+EPS&&Math.max(Math.min(a[1],b[1]),Math.min(c[1],d[1]))<=Math.min(Math.max(a[1],b[1]),Math.max(c[1],d[1]))+EPS)throw Error(FI.t("L’esquisse se croise. Déplacez ou supprimez les points concernés."));}if(Math.abs(polygonArea(p))<EPS)throw Error(FI.t("L’esquisse n’a pas de surface."));}
  function triangulate(input){const p=input.map(v=>v.slice());validatePolygon(p);if(polygonArea(p)<0)p.reverse();const ids=p.map((_,i)=>i),t=[];let guard=0;while(ids.length>3&&guard++<p.length*p.length){let found=false;for(let i=0;i<ids.length;i++){const ia=ids[(i+ids.length-1)%ids.length],ib=ids[i],ic=ids[(i+1)%ids.length],a=p[ia],b=p[ib],c=p[ic];if(cross2(a,b,c)<=1e-10)continue;const contains=ids.some(j=>j!==ia&&j!==ib&&j!==ic&&cross2(a,b,p[j])>=-1e-10&&cross2(b,c,p[j])>=-1e-10&&cross2(c,a,p[j])>=-1e-10);if(contains)continue;t.push([ia,ib,ic]);ids.splice(i,1);found=true;break;}if(!found)throw Error(FI.t("Triangulation impossible : évitez les points alignés ou trop proches."));}if(ids.length===3)t.push([...ids]);return {points:p,triangles:t};}
  function extrude(points,h){const {points:p,triangles:ts}=triangulate(points),out=[],z=h/2;for(const t of ts){tri(out,[...p[t[0]],z],[...p[t[1]],z],[...p[t[2]],z]);tri(out,[...p[t[2]],-z],[...p[t[1]],-z],[...p[t[0]],-z]);}for(let i=0;i<p.length;i++){const a=p[i],b=p[(i+1)%p.length];quad(out,[...a,-z],[...b,-z],[...b,z],[...a,z]);}return geometry(out);}
  function primitive(type,args={}){if(!defaults[type])throw Error(FI.t("Forme inconnue."));const p={...defaults[type],...args},out=[];for(const [k,v] of Object.entries(p))if(k!=='points'&&(!Number.isFinite(v)||v<0||v>100000))throw Error(FI.t("Paramètre invalide : ")+k);if(p.h!==undefined&&p.h<.01)throw Error(FI.t("La hauteur doit être positive."));const N=clamp(Math.round(p.segments||48),8,160),h=(p.h||1)/2;
    if(type==='box')return extrude([[-p.w/2,-p.d/2],[p.w/2,-p.d/2],[p.w/2,p.d/2],[-p.w/2,p.d/2]],p.h);
    if(type==='sketch')return center(extrude(p.points,p.h));
    if(type==='prism'||type==='gear'||type==='rounded'){
      const pts=[];
      if(type==='prism'){const n=clamp(Math.round(p.sides),3,32);for(let i=0;i<n;i++)pts.push([p.r*Math.cos(i*2*Math.PI/n),p.r*Math.sin(i*2*Math.PI/n)]);}
      if(type==='gear'){if(p.root>=p.r||p.root<=0)throw Error(FI.t("Le rayon intérieur doit être plus petit que le rayon extérieur."));const n=clamp(Math.round(p.teeth),5,60);for(let i=0;i<n*4;i++){const r=(i%4===1||i%4===2)?p.r:p.root,a=i*2*Math.PI/(n*4);pts.push([r*Math.cos(a),r*Math.sin(a)]);}}
      if(type==='rounded'){const r=Math.min(p.r,Math.min(p.w,p.d)/2-.001);if(r<=0)return primitive('box',p);const count=clamp(Math.round(p.segments),2,32),centers=[[p.w/2-r,p.d/2-r],[-p.w/2+r,p.d/2-r],[-p.w/2+r,-p.d/2+r],[p.w/2-r,-p.d/2+r]];for(let k=0;k<4;k++)for(let j=0;j<=count;j++){const a=k*Math.PI/2+j*Math.PI/(2*count);pts.push([centers[k][0]+r*Math.cos(a),centers[k][1]+r*Math.sin(a)]);}}
      return extrude(pts,p.h);
    }
    if(type==='wedge'){const w=p.w/2,d=p.d/2,z=p.h/2,a=[-w,-d,-z],b=[w,-d,-z],c=[-w,-d,z],A=[-w,d,-z],B=[w,d,-z],C=[-w,d,z];tri(out,a,b,c);tri(out,A,C,B);quad(out,a,A,B,b);quad(out,a,c,C,A);quad(out,b,B,C,c);return geometry(out);}
    if(type==='cylinder'||type==='cone'||type==='tube'){
      const r=p.r,rt=type==='cone'?p.top:r,ri=type==='tube'?p.inner:0;if(r<.01||ri>=r)throw Error(FI.t("Vérifiez les rayons : extérieur > intérieur ≥ 0."));
      for(let i=0;i<N;i++){const a=i*2*Math.PI/N,b=(i+1)*2*Math.PI/N,pt=(r,a,z)=>[r*Math.cos(a),r*Math.sin(a),z],A=pt(r,a,-h),B=pt(r,b,-h),C=pt(rt,b,h),D=pt(rt,a,h);quad(out,A,B,C,D);if(ri>0){const E=pt(ri,a,-h),F=pt(ri,b,-h),G=pt(ri,b,h),H=pt(ri,a,h);quad(out,F,E,H,G);quad(out,D,C,G,H);quad(out,B,A,E,F);}else{tri(out,[0,0,-h],B,A);tri(out,[0,0,h],D,C);}}
      return geometry(out);
    }
    if(type==='sphere'){const stacks=Math.max(6,Math.round(N/2)),v=(i,j)=>{const a=i*2*Math.PI/N,b=j*Math.PI/stacks;return [p.r*Math.sin(b)*Math.cos(a),p.r*Math.sin(b)*Math.sin(a),p.r*Math.cos(b)];};for(let j=0;j<stacks;j++)for(let i=0;i<N;i++)quad(out,v(i,j),v(i,j+1),v(i+1,j+1),v(i+1,j));return geometry(out);}
    if(type==='torus'){if(p.t>=p.r||p.t<.01)throw Error(FI.t("Le petit rayon doit être positif et inférieur au grand rayon."));const M=24,v=(i,j)=>{const a=i*2*Math.PI/N,b=j*2*Math.PI/M;return [(p.r+p.t*Math.cos(b))*Math.cos(a),(p.r+p.t*Math.cos(b))*Math.sin(a),p.t*Math.sin(b)];};for(let i=0;i<N;i++)for(let j=0;j<M;j++)quad(out,v(i,j),v(i+1,j),v(i+1,j+1),v(i,j+1));return geometry(out);}
    throw Error(FI.t("Forme non prise en charge."));
  }
  function parseSTL(buffer,unit=1){if(!(buffer instanceof ArrayBuffer))throw Error(FI.t("Fichier STL invalide."));if(buffer.byteLength>100*1024*1024)throw Error(FI.t("Fichier trop lourd (100 Mo maximum)."));let p;
    if(buffer.byteLength>=84){const dv=new DataView(buffer),n=dv.getUint32(80,true);if(n>0&&84+n*50<=buffer.byteLength&&buffer.byteLength-(84+n*50)<1024){if(n>MAX_TRIANGLES)throw Error(FI.t("Le STL dépasse 1 200 000 triangles."));p=new Float32Array(n*9);for(let i=0;i<n;i++)for(let k=0;k<9;k++)p[i*9+k]=dv.getFloat32(84+i*50+12+k*4,true)*unit;}}
    if(!p){const text=new TextDecoder().decode(buffer);if(!/^\s*solid(?:\s|$)/i.test(text))throw Error(FI.t("Ce fichier n’est pas un STL ASCII ou binaire reconnu."));const out=[],re=/\bvertex\s+([+-]?(?:\d+\.?\d*|\.\d+)(?:[eE][+-]?\d+)?)\s+([+-]?(?:\d+\.?\d*|\.\d+)(?:[eE][+-]?\d+)?)\s+([+-]?(?:\d+\.?\d*|\.\d+)(?:[eE][+-]?\d+)?)/g;let m;while((m=re.exec(text))){out.push(+m[1]*unit,+m[2]*unit,+m[3]*unit);if(out.length>MAX_TRIANGLES*9)throw Error(FI.t("Trop de triangles."));}p=new Float32Array(out);}
    return clean(geometry(p)).geo;
  }
  function exportSTL(geometries,binary=true,name='forma3d'){const arrays=geometries.map(g=>g.positions||g),count=arrays.reduce((s,p)=>s+p.length/9,0);if(!count)throw Error(FI.t("Rien à exporter."));if(binary){const buffer=new ArrayBuffer(84+count*50),dv=new DataView(buffer);new Uint8Array(buffer,0,80).set(new TextEncoder().encode('FORMA 3D | mesh coordinates expressed in millimetres').slice(0,80));dv.setUint32(80,count,true);let offset=84;for(const p of arrays)for(let i=0;i<p.length;i+=9){const n=normal(p.subarray(i,i+3),p.subarray(i+3,i+6),p.subarray(i+6,i+9));for(let k=0;k<3;k++)dv.setFloat32(offset+k*4,n[k],true);for(let k=0;k<9;k++)dv.setFloat32(offset+12+k*4,p[i+k],true);offset+=50;}return buffer;}
    const lines=['solid '+name.replace(/[^a-zA-Z0-9_-]/g,'_')];for(const p of arrays)for(let i=0;i<p.length;i+=9){const n=normal(p.subarray(i,i+3),p.subarray(i+3,i+6),p.subarray(i+6,i+9));lines.push(' facet normal '+n.join(' '),'  outer loop');for(let k=0;k<3;k++)lines.push('   vertex '+Array.from(p.subarray(i+k*3,i+k*3+3)).join(' '));lines.push('  endloop',' endfacet');}lines.push('endsolid');return lines.join('\n');
  }
  function topology(g){const p=g.positions,vertices=[],map=new Map(),faces=[],edges=new Map(),adj=[],occ=[];for(let i=0;i<p.length;i+=9){const t=[];for(let k=0;k<3;k++){const o=i+k*3,key=keyOf(p,o);let id=map.get(key);if(id===undefined){id=vertices.length;map.set(key,id);vertices.push(Array.from(p.subarray(o,o+3)));adj.push(new Set());occ.push([]);}t.push(id);occ[id].push(o);}const f=faces.length;faces.push(t);for(let k=0;k<3;k++){const a=t[k],b=t[(k+1)%3],key=a<b?a+':'+b:b+':'+a;if(!edges.has(key))edges.set(key,[]);edges.get(key).push({face:f,a,b});adj[a].add(b);adj[b].add(a);}}return {vertices,faces,edges,adj,occ};}
  function analyze(g){const t=topology(g);let boundary=0,nonManifold=0,inconsistent=0,area=0,volume=0,degenerate=0;for(const es of t.edges.values()){if(es.length===1)boundary++;if(es.length>2)nonManifold++;if(es.length===2&&es[0].a===es[1].a)inconsistent++;}const p=g.positions;for(let i=0;i<p.length;i+=9){const a=Array.from(p.subarray(i,i+3)),b=Array.from(p.subarray(i+3,i+6)),c=Array.from(p.subarray(i+6,i+9)),s=len(cross(sub(b,a),sub(c,a)))/2;area+=s;if(s<1e-10)degenerate++;volume+=dot(a,cross(b,c))/6;}return {triangles:p.length/9,vertices:t.vertices.length,boundary,nonManifold,inconsistent,area,volume:Math.abs(volume),signedVolume:volume,degenerate,closed:boundary===0&&nonManifold===0&&inconsistent===0&&degenerate===0};}
  function clean(g,orient=false){const out=[],seen=new Set(),p=g.positions;let removed=0;for(let i=0;i<p.length;i+=9){const a=Array.from(p.subarray(i,i+3)),b=Array.from(p.subarray(i+3,i+6)),c=Array.from(p.subarray(i+6,i+9)),key=[keyOf(a),keyOf(b),keyOf(c)].sort().join('|');if(len(cross(sub(b,a),sub(c,a)))<1e-10||seen.has(key)){removed++;continue;}seen.add(key);tri(out,a,b,c);}let geo=geometry(out);if(orient){const t=topology(geo),visited=new Uint8Array(t.faces.length),flip=new Uint8Array(t.faces.length),fa=Array.from({length:t.faces.length},()=>[]);for(const es of t.edges.values())if(es.length===2){const [a,b]=es,rel=+(a.a===b.a);fa[a.face].push([b.face,rel]);fa[b.face].push([a.face,rel]);}const pos=geo.positions.slice();for(let root=0;root<t.faces.length;root++)if(!visited[root]){const q=[root],component=[];visited[root]=1;while(q.length){const i=q.pop();component.push(i);for(const [j,r] of fa[i])if(!visited[j]){visited[j]=1;flip[j]=flip[i]^r;q.push(j);}}let volume=0;for(const i of component){const [a,b,c]=t.faces[i].map(j=>t.vertices[j]);volume+=dot(a,cross(b,c))/6*(flip[i]?-1:1);}for(const i of component)if(flip[i]^(volume<0))for(let k=0;k<3;k++)[pos[i*9+3+k],pos[i*9+6+k]]=[pos[i*9+6+k],pos[i*9+3+k]];}geo=geometry(pos);}return {geo,removed};}
  function connected(g){const t=topology(g),neighbors=Array.from({length:t.faces.length},()=>[]);for(const es of t.edges.values())for(let i=1;i<es.length;i++){neighbors[es[0].face].push(es[i].face);neighbors[es[i].face].push(es[0].face);}const seen=new Uint8Array(t.faces.length),result=[];for(let root=0;root<t.faces.length;root++)if(!seen[root]){const stack=[root],out=[];seen[root]=1;while(stack.length){const i=stack.pop();for(let k=0;k<9;k++)out.push(g.positions[i*9+k]);for(const j of neighbors[i])if(!seen[j]){seen[j]=1;stack.push(j);}}result.push(geometry(out));if(result.length>200)throw Error(FI.t("Plus de 200 composantes : nettoyez le maillage avant de séparer."));}return result;}
  function planarPatch(g,seed){const t=topology(g);if(seed<0||seed>=t.faces.length)throw Error(FI.t("Face invalide."));const pts=t.faces[seed].map(i=>t.vertices[i]),n=normal(...pts),w=dot(n,pts[0]),tol=Math.max(1e-4,Math.max(...g.bounds.size)*1e-6),ok=new Uint8Array(t.faces.length),neighbors=Array.from({length:t.faces.length},()=>[]);for(let i=0;i<t.faces.length;i++){const p=t.faces[i].map(j=>t.vertices[j]);if(dot(normal(...p),n)>.9998&&p.every(v=>Math.abs(dot(v,n)-w)<tol))ok[i]=1;}for(const es of t.edges.values())if(es.length===2){const a=es[0].face,b=es[1].face;if(ok[a]&&ok[b]){neighbors[a].push(b);neighbors[b].push(a);}}const ids=[],set=new Set([seed]),stack=[seed];while(stack.length){const i=stack.pop();ids.push(i);for(const j of neighbors[i])if(!set.has(j)){set.add(j);stack.push(j);}}const boundary=[];for(const es of t.edges.values()){const selected=es.filter(e=>set.has(e.face));if(selected.length===1)boundary.push([t.vertices[selected[0].a],t.vertices[selected[0].b]]);}return {ids,normal:n,boundary};}
  function patchPrism(g,patch,distance){if(Math.abs(distance)<.001)throw Error(FI.t("Saisissez une distance non nulle."));const n=patch.normal,e=.005,lo=distance>0?-e:distance,hi=distance>0?distance:e,out=[];for(const id of patch.ids){const p=Array.from({length:3},(_,k)=>Array.from(g.positions.subarray(id*9+k*3,id*9+k*3+3)));tri(out,...p.map(v=>add(v,mul(n,hi))));tri(out,...p.slice().reverse().map(v=>add(v,mul(n,lo))));}for(const [a,b] of patch.boundary)quad(out,add(a,mul(n,lo)),add(b,mul(n,lo)),add(b,mul(n,hi)),add(a,mul(n,hi)));return geometry(out);}
  function subdivide(g){if(g.positions.length/9>180000)throw Error(FI.t("Subdivision limitée à 180 000 triangles en entrée."));const out=[],p=g.positions;for(let i=0;i<p.length;i+=9){const a=Array.from(p.subarray(i,i+3)),b=Array.from(p.subarray(i+3,i+6)),c=Array.from(p.subarray(i+6,i+9)),ab=lerp(a,b,.5),bc=lerp(b,c,.5),ca=lerp(c,a,.5);tri(out,a,ab,ca);tri(out,ab,b,bc);tri(out,ca,bc,c);tri(out,ab,bc,ca);}return geometry(out);}
  function smoothMesh(g,iterations=1,strength=.25){const t=topology(g),fixed=new Set();for(const es of t.edges.values())if(es.length!==2)for(const e of es){fixed.add(e.a);fixed.add(e.b);}let verts=t.vertices;for(let it=0;it<iterations;it++)verts=verts.map((v,i)=>{if(fixed.has(i)||!t.adj[i].size)return v;let avg=[0,0,0];for(const j of t.adj[i])avg=add(avg,verts[j]);return lerp(v,mul(avg,1/t.adj[i].size),strength);});const p=g.positions.slice();for(let i=0;i<verts.length;i++)for(const o of t.occ[i])p.set(verts[i],o);return geometry(p);}
  function simplify(g,targetRatio=.6){/* Conservative vertex clustering; not a CAD feature reconstruction. */const b=g.bounds,max=Math.max(...b.size),target=g.positions.length/9*targetRatio;let best=g;for(let step=0;step<14;step++){const cell=max/(200/Math.pow(1.35,step)),cells=new Map(),p=g.positions;for(let i=0;i<p.length;i+=3){const key=p.subarray(i,i+3).map((v,k)=>Math.round((v-b.min[k])/cell)).join(',');let c=cells.get(key);if(!c){c={sum:[0,0,0],n:0};cells.set(key,c);}for(let k=0;k<3;k++)c.sum[k]+=p[i+k];c.n++;}const out=[];for(let i=0;i<p.length;i+=9){const vs=[];for(let j=0;j<3;j++){const o=i+j*3,key=p.subarray(o,o+3).map((v,k)=>Math.round((v-b.min[k])/cell)).join(','),c=cells.get(key);vs.push(mul(c.sum,1/c.n));}tri(out,...vs);}if(out.length){best=clean(geometry(out)).geo;if(best.positions.length/9<=target)break;}}return best;}
  return {EPS,MAX_TRIANGLES,geometry,tri,quad,center,transform,normal,normals,keyOf,defaults,primitive,triangulate,extrude,validatePolygon,parseSTL,exportSTL,topology,analyze,clean,connected,planarPatch,patchPrism,subdivide,smoothMesh,simplify};
})();
if(typeof module!=='undefined')module.exports=FG;
