/* FORMA 3D — native WebGL renderer, CAD camera and triangle picking. No network dependencies. */
'use strict';
var FRenderer=class{
 constructor(canvas,overlay){this.canvas=canvas;this.overlay=overlay;this.gl=canvas.getContext('webgl',{antialias:true,alpha:false,preserveDrawingBuffer:true});if(!this.gl)throw Error(FI.t("WebGL est indisponible. Activez l’accélération graphique du navigateur."));this.cache=new Map();this.objects=[];this.camera={target:[0,0,10],yaw:-Math.PI/4,pitch:Math.PI/3.5,distance:230,ortho:true};this.grid=true;this.wire=false;this.xray=false;this.stage=200;this.selected=new Set();this.frame=null;this.lost=false;this.init();new ResizeObserver(()=>this.resize()).observe(canvas.parentElement);canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();this.lost=true;this.onError?.(FI.t("Contexte graphique perdu. Sauvegardez le projet, puis rechargez la page."));});canvas.addEventListener('webglcontextrestored',()=>{this.lost=false;this.cache.clear();this.init();this.request();});this.resize();}
 init(){const gl=this.gl;const vs=`attribute vec3 aPosition;attribute vec3 aNormal;uniform mat4 uModel;uniform mat4 uVP;uniform mat3 uNormal;varying vec3 vNormal;varying vec3 vWorld;void main(){vec4 world=uModel*vec4(aPosition,1.);vWorld=world.xyz;vNormal=uNormal*aNormal;gl_Position=uVP*world;}`;const fs=`precision highp float;uniform vec4 uColor;uniform vec3 uEye;uniform float uFlat;varying vec3 vNormal;varying vec3 vWorld;void main(){vec3 n=normalize(vNormal);if(!gl_FrontFacing)n=-n;vec3 light=normalize(vec3(-.4,-.5,1.));float d=max(dot(n,light),0.);float fill=max(dot(n,normalize(vec3(.8,.4,.35))),0.);float shade=.47+.43*d+.16*fill;vec3 view=normalize(uEye-vWorld);float spec=pow(max(dot(n,normalize(light+view)),0.),32.)*.12;vec3 col=uColor.rgb*shade+vec3(spec);gl_FragColor=vec4(mix(col,uColor.rgb,uFlat),uColor.a);}`;
 const compile=(type,src)=>{const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;};this.program=gl.createProgram();const v=compile(gl.VERTEX_SHADER,vs),f=compile(gl.FRAGMENT_SHADER,fs);gl.attachShader(this.program,v);gl.attachShader(this.program,f);gl.linkProgram(this.program);gl.deleteShader(v);gl.deleteShader(f);if(!gl.getProgramParameter(this.program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(this.program));gl.useProgram(this.program);this.a={p:gl.getAttribLocation(this.program,'aPosition'),n:gl.getAttribLocation(this.program,'aNormal')};this.u={};for(const n of ['Model','VP','Normal','Color','Eye','Flat'])this.u[n]=gl.getUniformLocation(this.program,'u'+n);this.lineBuffer=gl.createBuffer();this.lineNormal=gl.createBuffer();gl.enable(gl.DEPTH_TEST);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.clearColor(.95,.96,.975,1);}
 resize(){const r=this.canvas.parentElement.getBoundingClientRect();this.w=Math.max(1,r.width);this.h=Math.max(1,r.height);this.dpr=Math.min(window.devicePixelRatio||1,2);for(const c of [this.canvas,this.overlay]){c.width=Math.round(this.w*this.dpr);c.height=Math.round(this.h*this.dpr);c.style.width=this.w+'px';c.style.height=this.h+'px';}this.request();}
 setScene(objects,selected){this.objects=objects;this.selected=new Set(selected);const alive=new Set(objects.map(o=>o.geo.id));for(const [id,c]of this.cache)if(!alive.has(id)){this.gl.deleteBuffer(c.p);this.gl.deleteBuffer(c.n);this.gl.deleteBuffer(c.edges);this.cache.delete(id);}this.request();}
 invalidate(id){const c=this.cache.get(id);if(c){this.gl.deleteBuffer(c.p);this.gl.deleteBuffer(c.n);this.gl.deleteBuffer(c.edges);this.cache.delete(id);}this.request();}
 matrices(){const c=this.camera,cp=Math.cos(c.pitch);this.eye=FM.add(c.target,[c.distance*cp*Math.cos(c.yaw),c.distance*cp*Math.sin(c.yaw),c.distance*Math.sin(c.pitch)]);this.view=FM.lookAt(this.eye,c.target,Math.abs(cp)<1e-5?[0,1,0]:[0,0,1]);const far=Math.max(2000,c.distance*100),near=Math.max(.001,c.distance/10000),span=c.distance*.42;this.projection=c.ortho?FM.ortho(-span*this.w/this.h,span*this.w/this.h,-span,span,near,far):FM.perspective(FM.rad(45),this.w/this.h,near,far);this.vp=FM.mm(this.projection,this.view);this.invVP=FM.inverse(this.vp);}
 model(o){return FM.compose(o.position,o.rotation,o.scale);}
 project(p){const v=FM.point(this.vp,p);return [(v[0]+1)*this.w/2,(1-v[1])*this.h/2,v[2]];}
 ray(x,y){this.matrices();const a=FM.point(this.invVP,[x/this.w*2-1,1-y/this.h*2,-1]),b=FM.point(this.invVP,[x/this.w*2-1,1-y/this.h*2,1]);return {origin:a,direction:FM.norm(FM.sub(b,a))};}
 pick(x,y,filter=null){const ray=this.ray(x,y);let hit=null;for(const o of this.objects){if(!o.visible||o.locked||(filter&&!filter(o)))continue;const m=this.model(o),inv=FM.inverse(m);if(!inv)continue;const orig=FM.point(inv,ray.origin),dir=FM.norm(FM.direction(inv,ray.direction));if(!FM.rayBox(orig,dir,o.geo.bounds))continue;const p=o.geo.positions;for(let i=0;i<p.length;i+=9){const a=p.subarray(i,i+3),b=p.subarray(i+3,i+6),c=p.subarray(i+6,i+9),t=FM.rayTriangle(orig,dir,a,b,c);if(t===null)continue;const local=FM.add(orig,FM.mul(dir,t)),world=FM.point(m,local),distance=FM.len(FM.sub(world,ray.origin));if(!hit||distance<hit.distance){const invm=FM.inverse(m),ln=FG.normal(a,b,c),normal=FM.norm([invm[0]*ln[0]+invm[1]*ln[1]+invm[2]*ln[2],invm[4]*ln[0]+invm[5]*ln[1]+invm[6]*ln[2],invm[8]*ln[0]+invm[9]*ln[1]+invm[10]*ln[2]]);hit={object:o,point:world,local,normal,face:i/9,distance};}}}return hit;}
 data(o){const gl=this.gl,g=o.geo;let c=this.cache.get(g.id);if(c&&c.smooth===o.smooth)return c;if(c)this.invalidate(g.id);const make=p=>{const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,p,gl.STATIC_DRAW);return b;};c={p:make(g.positions),n:make(FG.normals(g,o.smooth&&g.positions.length/9<=100000)),count:g.positions.length/3,smooth:o.smooth,edges:null};this.cache.set(g.id,c);return c;}
 setMatrix(m){const gl=this.gl,inv=FM.inverse(m)||FM.identity();gl.uniformMatrix4fv(this.u.Model,false,new Float32Array(m));gl.uniformMatrix3fv(this.u.Normal,false,new Float32Array([inv[0],inv[4],inv[8],inv[1],inv[5],inv[9],inv[2],inv[6],inv[10]]));}
 color(hex,alpha=1){const m=/^#?([0-9a-f]{6})$/i.exec(hex);const n=parseInt(m?m[1]:'8899aa',16);return [(n>>16&255)/255,(n>>8&255)/255,(n&255)/255,alpha];}
 drawMesh(o,overlay=false){const gl=this.gl,c=this.data(o);gl.bindBuffer(gl.ARRAY_BUFFER,c.p);gl.enableVertexAttribArray(this.a.p);gl.vertexAttribPointer(this.a.p,3,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ARRAY_BUFFER,c.n);gl.enableVertexAttribArray(this.a.n);gl.vertexAttribPointer(this.a.n,3,gl.FLOAT,false,0,0);this.setMatrix(this.model(o));gl.uniform4fv(this.u.Color,this.color(o.hole?'#94a3b8':o.color,o.hole?.25:this.xray?.38:1));gl.uniform1f(this.u.Flat,0);gl.enable(gl.POLYGON_OFFSET_FILL);gl.polygonOffset(1,1);gl.drawArrays(gl.TRIANGLES,0,c.count);gl.disable(gl.POLYGON_OFFSET_FILL);if(this.wire||o.hole){if(!c.edges){const p=o.geo.positions,e=new Float32Array(p.length*2);let k=0;for(let i=0;i<p.length;i+=9)for(let j=0;j<3;j++){e.set(p.subarray(i+j*3,i+j*3+3),k);k+=3;const n=(j+1)%3;e.set(p.subarray(i+n*3,i+n*3+3),k);k+=3;}c.edges=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,c.edges);gl.bufferData(gl.ARRAY_BUFFER,e,gl.STATIC_DRAW);}gl.bindBuffer(gl.ARRAY_BUFFER,c.edges);gl.vertexAttribPointer(this.a.p,3,gl.FLOAT,false,0,0);gl.disableVertexAttribArray(this.a.n);gl.vertexAttrib3f(this.a.n,0,0,1);gl.uniform4fv(this.u.Color,this.color(o.hole?'#718096':'#233a59',o.hole?.38:.24));gl.uniform1f(this.u.Flat,1);gl.drawArrays(gl.LINES,0,c.count*2);}}
 lines(points,color='#cbd2de',alpha=1){if(!points.length)return;const gl=this.gl;this.setMatrix(FM.identity());gl.bindBuffer(gl.ARRAY_BUFFER,this.lineBuffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(points),gl.DYNAMIC_DRAW);gl.enableVertexAttribArray(this.a.p);gl.vertexAttribPointer(this.a.p,3,gl.FLOAT,false,0,0);gl.disableVertexAttribArray(this.a.n);gl.vertexAttrib3f(this.a.n,0,0,1);gl.uniform4fv(this.u.Color,this.color(color,alpha));gl.uniform1f(this.u.Flat,1);gl.drawArrays(gl.LINES,0,points.length/3);}
 drawGrid(){const s=this.stage/2,minor=[],major=[],step=5;for(let i=-s;i<=s+.001;i+=step){const a=Math.abs(i%25)<.01?major:minor;a.push(-s,i,-.015,s,i,-.015,i,-s,-.015,i,s,-.015);}this.lines(minor,'#dce2ec');this.lines(major,'#c9d2e1');this.lines([-s,-s,0,s,-s,0,s,-s,0,s,s,0,s,s,0,-s,s,0,-s,s,0,-s,-s,0],'#98a8bf');this.lines([0,0,0,s,0,0],'#dd777f',.85);this.lines([0,0,0,0,s,0],'#68aa87',.85);}
 request(){if(this.frame||this.lost)return;this.frame=requestAnimationFrame(()=>{this.frame=null;this.render();});}
 render(){if(this.lost)return;this.matrices();const gl=this.gl;gl.viewport(0,0,this.canvas.width,this.canvas.height);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.useProgram(this.program);gl.uniformMatrix4fv(this.u.VP,false,new Float32Array(this.vp));gl.uniform3fv(this.u.Eye,this.eye);gl.depthMask(true);if(this.grid)this.drawGrid();const solid=this.objects.filter(o=>o.visible&&!o.hole),holes=this.objects.filter(o=>o.visible&&o.hole);for(const o of solid)this.drawMesh(o);gl.depthMask(false);for(const o of holes)this.drawMesh(o);gl.depthMask(true);if(this.facePreview){this.lines(this.facePreview,'#f39c38',1);}this.drawOverlay?.();}
 fit(objects=this.objects.filter(o=>o.visible)){if(!objects.length){this.camera.target=[0,0,0];this.camera.distance=230;this.request();return;}const pts=[];for(const o of objects)for(const p of FM.corners(o.geo.bounds))pts.push(...FM.point(this.model(o),p));const b=FM.bounds(pts);this.camera.target=b.center;this.camera.distance=Math.max(25,FM.len(b.size)*1.65,Math.max(...b.size)*this.h/this.w*1.6);this.request();}
 viewPreset(name){const c=this.camera;if(name==='iso'){c.yaw=-Math.PI/4;c.pitch=Math.PI/3.5;}if(name==='top'){c.yaw=-Math.PI/2;c.pitch=Math.PI/2-.00001;}if(name==='bottom'){c.yaw=-Math.PI/2;c.pitch=-Math.PI/2+.00001;}if(name==='front'){c.yaw=-Math.PI/2;c.pitch=.00001;}if(name==='back'){c.yaw=Math.PI/2;c.pitch=.00001;}if(name==='right'){c.yaw=0;c.pitch=.00001;}if(name==='left'){c.yaw=Math.PI;c.pitch=.00001;}this.request();}
 pan(dx,dy){const right=[this.view[0],this.view[4],this.view[8]],up=[this.view[1],this.view[5],this.view[9]],f=this.camera.distance*.84/this.h;this.camera.target=FM.add(this.camera.target,FM.add(FM.mul(right,-dx*f),FM.mul(up,dy*f)));this.request();}
};
