/* Versioned project files and local autosave. No cookies, analytics, or remote services. */
'use strict';
var FStore=(()=>{
 const b64encode=buffer=>{const bytes=new Uint8Array(buffer),chunks=[];for(let i=0;i<bytes.length;i+=24576)chunks.push(String.fromCharCode(...bytes.subarray(i,i+24576)));return btoa(chunks.join(''));};
 function b64decode(s){if(typeof s!=='string'||s.length>80*1024*1024)throw Error(FI.t("Bloc de maillage invalide ou trop volumineux."));const bin=atob(s),a=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)a[i]=bin.charCodeAt(i);if(a.length%36)throw Error(FI.t("Maillage incomplet dans le projet."));return new Float32Array(a.buffer);}
 function pack(state,binary=true){const geometries=Object.create(null),objects=state.objects.map(o=>{if(!geometries[o.geo.id])geometries[o.geo.id]={positions:binary?o.geo.positions.slice():b64encode(o.geo.positions.buffer.slice(o.geo.positions.byteOffset,o.geo.positions.byteOffset+o.geo.positions.byteLength))};return {id:o.id,name:o.name,position:o.position.slice(),rotation:o.rotation.slice(),scale:o.scale.slice(),color:o.color,visible:o.visible,locked:o.locked,hole:o.hole,smooth:o.smooth,param:o.param?JSON.parse(JSON.stringify(o.param)):null,geo:o.geo.id};});return {format:'forma3d',version:1,units:'mm',title:state.name,createdWith:'FORMA 3D 1.0',encoding:binary?'float32':'base64-f32-le',geometries,objects};}
 function unpack(data){if(!data||data.format!=='forma3d'||data.version!==1||!Array.isArray(data.objects)||!data.geometries||data.units!=='mm')throw Error(FI.t("Ce fichier n’est pas un projet FORMA 3D version 1."));if(data.objects.length>300)throw Error(FI.t("Maximum : 300 objets par projet."));const cache=new Map(),ids=new Set();let total=0;const vec=(v,n)=>{if(!Array.isArray(v)||v.length!==n||!v.every(x=>typeof x==='number'&&Number.isFinite(x)&&Math.abs(x)<1e8))throw Error(FI.t("Transformation invalide."));return v.slice();};const objects=data.objects.map(o=>{if(typeof o.geo!=='string'||!Object.prototype.hasOwnProperty.call(data.geometries,o.geo))throw Error(FI.t("Référence de géométrie manquante."));let g=cache.get(o.geo);if(!g){const raw=data.geometries[o.geo].positions,p=typeof raw==='string'?b64decode(raw):raw instanceof Float32Array?raw:new Float32Array(raw);total+=p.byteLength;if(total>180*1024*1024)throw Error(FI.t("Projet trop volumineux (180 Mo de géométrie)."));g=FG.geometry(p);cache.set(o.geo,g);}const s=vec(o.scale,3);if(s.some(x=>x<.0001||x>10000))throw Error(FI.t("Échelle de projet non valide."));const q=vec(o.rotation,4);if(FM.len(q)<1e-9)throw Error(FI.t("Rotation invalide."));let id=typeof o.id==='string'?o.id:FM.uid();if(ids.has(id))id=FM.uid();ids.add(id);let param=null;if(o.param&&typeof o.param==='object'&&Object.hasOwn(FG.defaults,o.param.type)){try{FG.primitive(o.param.type,o.param.args);param=JSON.parse(JSON.stringify(o.param));}catch{param=null;}}return {id,name:String(o.name||FI.t("Objet")).slice(0,100),position:vec(o.position,3),rotation:FM.norm(q),scale:s,color:/^#[0-9a-f]{6}$/i.test(o.color)?o.color:'#6581ec',visible:o.visible!==false,locked:!!o.locked,hole:!!o.hole,smooth:!!o.smooth,param,geo:g};});return {name:String(data.title||FI.t("Projet importé")).slice(0,80),objects};}
 let dbPromise;
 function database(){if(!dbPromise)dbPromise=new Promise((resolve,reject)=>{if(!globalThis.indexedDB){reject(Error(FI.t("Stockage local indisponible.")));return;}const req=indexedDB.open('forma3d-local-v1',1);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains('projects'))req.result.createObjectStore('projects');};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);req.onblocked=()=>reject(Error(FI.t("Stockage local bloqué par un autre onglet.")));});return dbPromise;}
 async function write(data){const db=await database();return new Promise((res,rej)=>{const tx=db.transaction('projects','readwrite');tx.objectStore('projects').put(data,'autosave');tx.oncomplete=res;tx.onerror=()=>rej(tx.error);tx.onabort=()=>rej(tx.error);});}
 async function read(){const db=await database();return new Promise((res,rej)=>{const tx=db.transaction('projects','readonly'),req=tx.objectStore('projects').get('autosave');req.onsuccess=()=>res(req.result);req.onerror=()=>rej(req.error);});}
 return {pack,unpack,write,read};
})();
